# Configuration File Template
# Fill in the required information below.

paths:
  # Path to the pre-trained model (.pt file)
  pt_path: /path/to/pretrained/model.pt

  # Path to the Python script that contains the model
  model_python_path: /path/to/model/model.py

inputs:
  # List of input files (use '-' to list each file on a new line)
  input_list:
    - 1
    - 2

  # List of perturbation methods (use '-' to list each method)
  perturbation_list:
    - 1
    - 2

outputs:
  # Range of output values (e.g., "0-1" for normalized output)
  output_upper: 1

  # Number of output classes or required outputs
  output_lower: 0

other:
  # Path where the outputs should be saved
  output_path: ./output #default

  # Additional numeric value for custom purposes
  number: 10
